<a href="https://colab.research.google.com/github/shubhamk2001/Deep-Learning-Basics/blob/main/Tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.17.0


In [ ]:
hello = tf.constant('Hello')

In [ ]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
tf.print(hello)

Hello


In [ ]:
world = tf.constant("World")

In [ ]:
tf.print(world)

World


In [ ]:
result = hello + world
tf.print(result)

HelloWorld


In [ ]:
a = tf.constant(10)
b= tf.constant(20)
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
tf.print(a+b)

30


In [ ]:
myarr = tf.fill((5,5),10)
tf.print(myarr)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [ ]:
a = tf.constant([[4,5],[6,7]])

In [ ]:
a.get_shape()

TensorShape([2, 2])

In [ ]:
b = tf.constant([[8],[9]])

In [ ]:
b.get_shape()

TensorShape([2, 1])

In [ ]:
# creating a random numbers using tensors
mytensor = tf.random.normal((4,4),0,1)

In [ ]:
tf.print(mytensor)

[[0.97449261 0.742087662 1.69071186 -0.797817826]
 [0.760759294 -0.141116485 -1.0210216 0.545667887]
 [0.184215158 -1.68856263 -1.08437228 -0.626254797]
 [1.94173121 -1.64939 0.184510142 -1.73356235]]


In [ ]:
# Executing eagerly means executing the code line by line as in previous versions it's done through sessions.
if(tf.executing_eagerly()):
    print("True")
else:
    print("False")

True


# Simple Operations

In [ ]:
# making a constant tensor A, that does not change
A = tf.constant([[1,2],
                [3,4],[9,8]])

In [ ]:
tf.print(A)
A.numpy() # if you want to use it as a numpy array

[[1 2]
 [3 4]
 [9 8]]


array([[1, 2],
       [3, 4],
       [9, 8]], dtype=int32)

In [ ]:
# making a variable tensor
VA = tf.Variable([[1,7],
                [3,9],[4,5]])
# making a another tensor B
B = tf.constant([[4,5],
                [6,7],[3,3]])

In [ ]:
tf.print(B)

[[4 5]
 [6 7]
 [3 3]]


# Concatenation by tf.concat

In [ ]:
# concatenate columns
AB_concat = tf.concat(values=[A,B],axis=1)
tf.print(AB_concat)

[[1 2 4 5]
 [3 4 6 7]
 [9 8 3 3]]


In [ ]:
# concatenate rows
AB_concat = tf.concat(values=[A,B],axis=0)
tf.print(AB_concat)

[[1 2]
 [3 4]
 [9 8]
 [4 5]
 [6 7]
 [3 3]]


In [ ]:
# making a tensor filled with zeroes, shape = [rows, column]
zeroes = tf.zeros(shape=[2,2])
tf.print(zeroes)

[[0 0]
 [0 0]]


In [ ]:
# making a tensor filled with ones with data type of float32
ones = tf.ones(shape=[2,2],dtype=tf.float32)
tf.print(ones)

[[1 1]
 [1 1]]


# Reshape data by using tf.reshape

In [ ]:
# making a 4x3 tensor for rehsaping
tensor1 = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9],
                      [10,11,12]])

In [ ]:
# Reshaping the tensor into the shape of : shape = [rows, columns]
tensor_reshape = tf.reshape(tensor1,shape=(2,6))
tf.print(tensor_reshape)


[[1 2 3 4 5 6]
 [7 8 9 10 11 12]]


# Casting tensor to other data types by using tf.cast

In [ ]:
# making tensor
tensor2 = tf.constant([[1.3,2.5,3.6],
                      [4.4,5.3,6.1],
                      [7.2,8.7,9.2]], dtype=tf.float32)
tensor_as_int = tf.cast(tensor2,dtype=tf.int32)
tf.print(tensor_as_int)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# The linear algebra operations

In [ ]:
# Transpose tensor for a matrix
A = tf.constant([[1,2,5],
                [3,4,7],
                [5,6,2]])
A_transpose = tf.transpose(A)
tf.print(A_transpose)


[[1 3 5]
 [2 4 6]
 [5 7 2]]


In [ ]:
# Matrix Multiplication
A = tf.constant([[1,2],
                [3,4],
                [5,6]])
B = tf.constant([[1,2,3],
                [4,5,6]])
AB = tf.matmul(A,B)
tf.print(AB)

[[9 12 15]
 [19 26 33]
 [29 40 51]]


In [ ]:
# Element multiplication, shape of both the matrix should be equal
A = tf.constant([[1,2],
                [3,4],
                [5,6]])
B = tf.constant([[1,2],
                [3,4],
                [5,6]])
AB = tf.multiply(A,B)
tf.print(AB)
Av = tf.multiply(A,A)
tf.print(Av)

[[1 4]
 [9 16]
 [25 36]]
[[1 4]
 [9 16]
 [25 36]]


In [ ]:
# Identity matrix
A = tf.constant([[1,2],
                [3,4]])
rows, columns = A.shape
A_identity = tf.eye(num_rows=rows,num_columns=columns)
tf.print(A_identity)

[[1 0]
 [0 1]]


# Creating a variable in tensorflow

In [ ]:
# create a variable
var1 = tf.Variable(tf.zeros([2,3,4]))
tf.print(var1)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
v = tf.Variable(0.0)
w = v + 1
# w is a tf.Tensor which is computed based on the value of v
# Any time the variable is used in an expression it gets automatically converted to tf.Tensor representing it's value.

In [ ]:
tf.print(v)
tf.print(w)

0
1


In [ ]:
v = tf.Variable(0.0)
v.assign(2).numpy()

2.0

In [ ]:
tf.print(v)
v.assign_add(1).numpy()

2


3.0

# Operations in tensorflow

In [ ]:
def add_op(a,b):
    return a+b

In [ ]:
print(add_op(11,10))

21


In [ ]:
# Linear Model
W = tf.Variable([11],tf.int32)
b = tf.Variable([10],tf.int32)

In [ ]:
def linear_model(x):
    return W*x + b

In [ ]:
linear_model(x=[10,20,30,40]).numpy()

array([120, 230, 340, 450], dtype=int32)